In [1]:
import pandas as pd
import numpy as np
 
import seaborn as sns
from matplotlib import pyplot as plt

import wget

ANS Q1:

In [2]:
np.__version__

'1.19.5'

---------------------------------------------------------------------------------------------------------------------------------------------------



ANS Q2:

In [3]:
pd.__version__

'1.1.5'

-----------------------------------------------------------------------------------------
Get The Data : Car Prices

In [7]:
!wget --no-check-certificate \ https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2021-10-05 08:17:38--  http://%5C/
Resolving \\ (\\)... failed: No such host is known. .
wget: unable to resolve host address '\\'
--2021-10-05 08:17:38--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: 'data.csv.2'

     0K .......... .......... .......... .......... ..........  3% 1.17M 1s
    50K .......... .......... .......... .......... ..........  6% 1.71M 1s
   100K .......... .......... .......... .......... .......... 10% 1.21M 1s
   150K .......... .......... .......... .......... .......... 13% 3.40M 1s
   200K .......... .......... .......... .......... 

In [6]:
df = pd.read_csv('data.csv')
len(df)

11914

In [ ]:
df.head(3)

Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350

[3 rows x 16 columns]

-----------------------------------------------------------------------------------
ANS Q3:

In [ ]:
df_BMW = df[df["Make"] == "BMW"] 
len(df_BMW)

334

In [ ]:
mean = df_BMW["MSRP"].mean()
print(mean)

61546.76347305389


------------------------------------------------------------------------------
ANS Q4:

In [ ]:
df_after_2015 = df[df["Year"] >= 2015]
len(df_after_2015)

5995

In [ ]:
df_after_2015.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

----------------------------------------------------------------------------------
ANS Q5:

In [ ]:
initial_mean = df_after_2015["Engine HP"].mean()
print(round(initial_mean))

273


In [ ]:
df_after_2015["Engine HP"].fillna(int(df_after_2015["Engine HP"].mean()), inplace=True)
df_after_2015.isna().sum()

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:4536: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP               0
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [ ]:
new_mean = df_after_2015["Engine HP"].mean()
print(round(new_mean))

273


-------------------------------------------------------------------------------
ANS Q6:

In [ ]:
df_RR = df[df["Make"] == "Rolls-Royce"] 
print("Data Length :" ,len(df_RR))
print(df_RR)

Data Length : 31
              Make                   Model  Year  ... city mpg  Popularity    MSRP
2921   Rolls-Royce                Corniche  2001  ...       10          86  359990
3505   Rolls-Royce                    Dawn  2016  ...       12          86  335000
5275   Rolls-Royce         Ghost Series II  2015  ...       13          86  286750
5276   Rolls-Royce         Ghost Series II  2015  ...       13          86  319400
5277   Rolls-Royce         Ghost Series II  2016  ...       13          86  295850
5278   Rolls-Royce         Ghost Series II  2016  ...       13          86  329325
5279   Rolls-Royce                   Ghost  2012  ...       13          86  250000
5280   Rolls-Royce                   Ghost  2012  ...       13          86  290000
5281   Rolls-Royce                   Ghost  2013  ...       13          86  296000
5282   Rolls-Royce                   Ghost  2013  ...       13          86  256650
5283   Rolls-Royce                   Ghost  2014  ...       13        

In [ ]:
df_RR = df_RR[["Engine HP", "Engine Cylinders", "highway MPG"]]
df_RR.head()

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19
5275      563.0              12.0           21
5276      563.0              12.0           21
5277      563.0              12.0           21

In [ ]:
new_df_RR = df_RR.drop_duplicates()
print(new_df_RR)

       Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21


In [ ]:
X = new_df_RR.to_numpy()
print(X)

[[325.   8.  15.]
 [563.  12.  19.]
 [563.  12.  21.]
 [563.  12.  20.]
 [322.  12.  15.]
 [453.  12.  19.]
 [624.  12.  21.]]


In [ ]:
XTX = X.transpose().dot(X)
print(XTX)

[[1.754801e+06 3.965600e+04 6.519600e+04]
 [3.965600e+04 9.280000e+02 1.500000e+03]
 [6.519600e+04 1.500000e+03 2.454000e+03]]


In [ ]:
XTX = np.linalg.inv(XTX)
print(XTX)

[[ 5.17815728e-05  9.06587044e-04 -1.92984188e-03]
 [ 9.06587044e-04  1.05723058e-01 -8.87084092e-02]
 [-1.92984188e-03 -8.87084092e-02  1.05900809e-01]]


In [ ]:
XTX.sum()

0.032212320677486125

---------------------------------------------------------------------------
ANS Q7:

In [ ]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
print(y)

[1000 1100  900 1200 1000  850 1300]


In [ ]:
w = XTX.dot(X.transpose())
print("w before multiply with y = \n", w)
print(" ")
w = w.dot(y)
print("w after multiply with y = \n", w)

w before multiply with y = 
 [[-0.00486592  0.00336507 -0.00049461  0.00143523 -0.00139492 -0.0023309
   0.00266407]
 [-0.19020088  0.09362543 -0.08379139  0.00491702  0.22997159 -0.00609915
  -0.02848958]
 [ 0.25164625 -0.13888652  0.0729151  -0.03298571 -0.09739786  0.07339609
  -0.04480526]]
 
w after multiply with y = 
 [ 0.19989598 31.02612262 31.65378877]
